---
- name: Check if .pgpass file exists
  stat:
    path: "{{ pg_user_home }}/.pgpass"
  register: pgpass_stat

- name: Create .pgpass for user postgres
  file:
    path: "{{ pg_user_home }}/.pgpass"
    state: touch
    owner: "{{ pg_user }}"
    group: "{{ pg_group }}"
    mode: 0600
  when: not pgpass_stat.stat.exists

- name: Add roles to .pgpass file (hostname:port:database:username:password)
  command: |
    psql -t <<'SQL' 
      COPY(SELECT '{{ item.hostname }}:{{ item.port }}:{{ item.database }}:{{ item.name }}:'||passwd 
      FROM pg_shadow 
      WHERE usename = '{{ item.name }}') 
      TO STDOUT
    SQL >> "{{ pg_user_home }}"/.pgpass
  with_items: "{{ pg_pass_roles }}"
  when: pg_pass_roles | length > 0
  become: true
  become_user: "{{ pg_user }}"
  args:
    warn: false
