---
- name: Configure host based authentication
  postgresql_pg_hba:
    dest: "{{ pg_data_dir }}/pg_hba.conf"
    contype: "{{ item.type }}"
    databases: "{{ item.database }}"
    users: "{{ item.user }}"
    source: "{{ item.address }}"
    method: "{{ item.auth_method }}"
    state: "{{ item.state }}"
  with_items: "{{ pg_hba_entries }}"
  when: pg_hba_entries | length > 0
  no_log: true
  become: true
  become_user: "{{ pg_user }}"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true

- name: Set postgres superuser's database cluster password
  postgresql_query:
    port: "{{ pg_port }}"
    query: "ALTER ROLE {{ pg_superuser }} WITH PASSWORD '{{ pg_superuser_password }}';"
  become: true
  become_user: "{{ pg_user }}"
  when: pg_superuser_password | length > 0
  changed_when: false

- name: Configure global settings in postgresql.auto.conf
  postgresql_set:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items: "{{ pg_postgresql_conf_params }}"
  when: pg_postgresql_conf_params | length > 0
  no_log: true
  become: true
  become_user: "{{ pg_user }}"
  notify: restart postgresql
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true
