---
- name: Check if profile file exists
  stat:
    path: "{{ pg_user_home }}/{{ pg_profile_filename }}"
  register: pgsql_profile_stat

- name: Create profile for user
  file:
    path: "{{ pg_user_home }}/{{ pg_profile_filename }}"
    state: touch
    owner: "{{ pg_user }}"
    group: "{{ pg_group }}"
    mode: 0700
  when: not pgsql_profile_stat.stat.exists

- name: Add PostgreSQL environment variables
  lineinfile:
    dest: "{{ pg_user_home }}/{{ pg_profile_filename }}"
    insertafter: EOF
    line: "export {{ item }}"
    state: present
  with_items: "{{ pg_env_vars }}"
  when: pg_env_vars | length > 0
