---
- name: Check if .pgsql_profile file exists
  stat:
    path: "{{ pg_user_home }}/.pgsql_profile"
  register: pgsql_profile_stat

- name: Create .pgsql_profile for user postgres
  file:
    path: "{{ pg_user_home }}/.pgsql_profile"
    state: touch
    owner: "{{ pg_user }}"
    group: "{{ pg_group }}"
    mode: 0700
  when: not pgsql_profile_stat.stat.exists

- name: Add PostgreSQL environment variables
  lineinfile:
    dest: "{{ pg_user_home }}/.pgsql_profile"
    insertafter: EOF
    line: "export {{ item }}"
    state: present
  with_items: "{{ pg_env_vars }}"
  when: pg_env_vars | length > 0
