---
- name: Create PostgreSQL data directory
  file:
    path: "{{ pg_data_dir }}"
    owner: "{{ pg_user }}"
    group: "{{ pg_group }}"
    mode: 0700
    state: directory

- name: Create Unix socket domain directories
  file:
    path: "{{ item }}"
    owner: "{{ pg_user }}"
    group: "{{ pg_group }}"
    mode: 02775
    state: directory
  with_items: "{{ pg_unix_socket_directories }}"
  when: pg_unix_socket_directories | length > 0

- name: Create custom directories
  file:
    path: "{{ item.path }}"
    owner: "{{ pg_user }}"
    group: "{{ pg_group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items: "{{ pg_custom_dirs }}"
  when: pg_custom_dirs | length > 0
