---
- name: Create PostgreSQL data directory
  file:
    path: "{{ pg_data_dir }}"
    owner: "{{ pg_user }}"
    group: "{{ pg_group }}"
    mode: 0700
    state: directory

- name: Create Unix socket domain directory
  file:
    path: "{{ pg_unix_socket_directory | default('/var/run/postgresql') }}"
    owner: "{{ pg_user }}"
    group: "{{ pg_group }}"
    mode: 0744
    state: directory

- name: Create log directory
  file:
    path: "{{ pg_log_dir }}"
    owner: "{{ pg_user }}"
    group: "{{ pg_group }}"
    mode: 0744
    state: directory
  when: pg_log_dir | length > 0

- name: Create WAL archive directory
  file:
    path: "{{ pg_wal_archive_dir }}"
    owner: "{{ pg_user }}"
    group: "{{ pg_group }}"
    mode: 0744
    state: directory
  when: pg_wal_archive_dir | length > 0
