---
- name: Set postgres user's OS password
  user:
    name: "{{ pg_user }}"
    password: "{{ pg_user_password | password_hash('sha512') }}"
    update_password: always
    state: present
  when: pg_user_password | length > 0
  changed_when: false
  tags:
    - skip_ansible_lint

- name: Check if log directory exists
  stat:
    path: "{{ pg_log_dir }}"
  register: pg_log_dir_stat
  when: pg_log_dir | length > 0

- name: Create log directory
  file:
    path: "{{ pg_log_dir }}"
    state: directory
    owner: "{{ pg_user }}"
    group: "{{ pg_group }}"
    mode: '0744'
  when:
    - pg_log_dir | length > 0
    - not pg_log_dir_stat.stat.exists

- name: Check if WAL archive directory exists
  stat:
    path: "{{ pg_wal_archive_dir }}"
  register: pg_wal_archive_dir_stat
  when: pg_wal_archive_dir | length > 0

- name: Create WAL archive directory
  file:
    path: "{{ pg_wal_archive_dir }}"
    state: directory
    owner: "{{ pg_user }}"
    group: "{{ pg_group }}"
    mode: '0744'
  when:
    - pg_wal_archive_dir | length > 0
    - not pg_wal_archive_dir_stat.stat.exists

- name: Check if .pgsql_profile file exists
  stat:
    path: "{{ pg_user_home }}/.pgsql_profile"
  register: pgsql_profile_stat

- name: Create .pgsql_profile for user postgres
  file:
    path: "{{ pg_user_home }}/.pgsql_profile"
    state: touch
    owner: "{{ pg_user }}"
    group: "{{ pg_group }}"
    mode: 0700
  when: not pgsql_profile_stat.stat.exists

- name: Add PostgreSQL environment variables
  lineinfile:
    dest: "{{ pg_user_home }}/.pgsql_profile"
    insertafter: EOF
    line: "export {{ item }}"
    state: present
  with_items: "{{ pg_env_vars }}"
  when: pg_env_vars | length > 0

- name: Ensure PostgreSQL data directory exists
  file:
    path: "{{ pg_data_dir }}"
    owner: "{{ pg_user }}"
    group: "{{ pg_group }}"
    state: directory
    mode: 0700

- name: Check if PostgreSQL cluster is initialized
  stat:
    path: "{{ pg_data_dir }}/PG_VERSION"
  register: pgdata_dir_version

- name: Ensure PostgreSQL cluster is initialized
  command: "{{ pg_bin_path }}/initdb -D {{ pg_data_dir }} {{ pg_initdb_params }}"
  when: not pgdata_dir_version.stat.exists
  become: true
  become_user: "{{ pg_user }}"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true

- name: Ensure PostgreSQL unix socket directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ pg_user }}"
    group: "{{ pg_group }}"
    mode: 02775
  with_items: "{{ pg_unix_socket_directories }}"

- name: Create RAM-disk for pg_stat_tmp
  mount:
    backup: true
    path: "{{ pg_data_dir }}/pg_stat_tmp"
    src: tmpfs
    fstype: tmpfs
    opts: "size={{ pg_stat_tmp_ram_size }},uid={{ pg_user }},gid={{ pg_group }}"
    state: mounted
  when: pg_stat_tmp_on_ram_disk|default(false)
