---
- name: Stop PostgreSQL service
  command: /bin/true
  notify: stop postgresql

- name: Remove old PostgreSQL cluster directory
  file:
    path: "{{ pg_data_dir }}/"
    state: absent

- name: Create PostgreSQL data directory
  file:
    path: "{{ pg_data_dir }}"
    owner: "{{ pg_user }}"
    group: "{{ pg_group }}"
    mode: 0700
    state: directory

- name: Clone cluster directory of master
  command: "pg_basebackup -c fast -X stream -R -h {{ pg_master_ip }} -p {{ pg_port }} -U {{ pg_replication_user }} -D {{ pg_data_dir }}"
  become: true
  become_user: "{{ pg_user }}"
  notify: start enable postgresql