---
- name: Check if PostgreSQL cluster is initialized
  stat:
    path: "{{ pg_data_dir }}/PG_VERSION"
  register: pgdata_dir_version

- name: Ensure PostgreSQL cluster is initialized
  command: "{{ pg_bin_path }}/initdb -D {{ pg_data_dir }} {{ pg_initdb_params }}"
  when: not pgdata_dir_version.stat.exists
  become: true
  become_user: "{{ pg_user }}"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true

- name: Start enable postgresql
  service:
    name: "{{ pg_service }}"
    state: started
    enabled: "{{ pg_service_enabled }}"
