---
- name: Add EPEL repository
  yum:
    name: epel-release
    state: latest
  tags:
    - skip_ansible_lint

- name: Exclude CentOS PostgreSQL packages
  ini_file:
    path: /etc/yum.repos.d/CentOS-Base.repo
    option: exclude
    value: postgresql*
    section: "{{ item }}"
  with_items:
    - base
    - updates

- name: Add Yum repository
  yum:
    name: "{{ pg_repo_url }}"
    state: present

- name: create systemd override directory
  file:
    path: /etc/systemd/system/postgresql-{{ pg_major_version }}.service.d
    state: directory
  when: ansible_distribution_major_version == "7"

- name: add systemd override
  template:
    src: override-postgresql-{{ pg_major_version }}.j2
    dest: /etc/systemd/system/postgresql-{{ pg_major_version }}.service.d/override.conf

- name: Set username and password for EDB Yum repository
  replace:
    path: /etc/yum.repos.d/edb.repo
    regexp: '<username>:<password>'
    replace: "{{ edb_yum_username }}:{{ edb_yum_password }}"
  when: pg_type == 'edb'

- name: Ensure PostgreSQL packages are installed
  yum:
    name: "{{ pg_packages }}"
    state: present
    enablerepo: "{{ pg_enablerepo | default(omit, true) }}"
    # Don't let postgresql-contrib cause the /usr/bin/python symlink
    # to be installed, which breaks later Ansible runs on Fedora 30,
    # and affects system behavior in multiple ways.
    exclude: python-unversioned-command

- name: Ensure PostgreSQL Python libraries are installed
  yum:
    name: "{{ pg_python_libraries }}"
    state: present
    enablerepo: "{{ pg_enablerepo | default(omit, true) }}"

- name: Set postgres user's OS password
  user:
    name: "{{ pg_user }}"
    password: "{{ pg_user_password | password_hash('sha512') }}"
    update_password: always
    state: present
  when: pg_user_password | length > 0
  changed_when: false
  tags:
    - skip_ansible_lint

