---
- name: Include Community PostgreSQL specific variables
  include_vars: "pg_vars.yml"
  when: pg_type == 'pg'

- name: Check if EDB Yum repository file exists
  stat:
    path: /etc/yum.repos.d/edb.repo
  register: edb_yum_credentials_stat
  when: pg_type == 'edb'

- name: Include credentials for EnterpriseDB Yum repository
  include_vars: edb_yum_credentials.yml
  when: pg_type = 'edb'
  failed_when: not edb_yum_credentials_stat.stat.exists

- name: Include EnterpriseDB specific variables
  include_vars: "edb_vars.yml"
  when:
  when: pg_type == 'edb'
