---
- name: start postgresql
  service:
    name: "{{ pg_service }}"
    state: started

- name: reload postgresql
  service:
    name: "{{ pg_service }}"
    state: reloaded

- name: restart postgresql
  service:
    name: "{{ pg_service }}"
    state: restarted

- name: stop postgresql
  service:
    name: "{{ pg_service }}"
    state: stopped
